#!/bin/sh

## dkeg 2015
## battery status and level driven window borders 
## source in focus.sh -> fcs

. $HOME/bin/colr
## colors 
R=$bred
M=$mag
Y=$ylw
G=$grn
BG=$bgrn
C=$cyn
N=$bblk
W=$wht
BY=$bylw
F=$fg
BK=$blk
BBK=$bblk
## get the information
BATT=/sys/class/power_supply/BAT0
CAPACITY=$(cat $BATT/capacity)
STATE=$(cat $BATT/status)

## filter and colorize 
 if [ ${STATE} = "Discharging" ] ; then
   case ${CAPACITY} in
      [0-9])   bb="$R" ;;
      [0-1]*)  bb="$Y" ;;
      [2-9]*)  bb="$BBK" ;;
      [100])   bb="$G" ;;
   esac
 else 
   bb="$BBK"
 fi
