#!/bin/bash

## update gtk color from xcolor
## requires $HOME/.themes directory
## creates $HOME/tmp directory if doesn't exist
## requires an xcolor scraper from xrdb; or use colr
## dkeg 2015

. $HOME/bin/colr

# merge in case we forgot
xrdb merge ~/.Xresources

# create the directory if it doesn't exist 
dir=$HOME/tmp
if [[ ! -d "{$dir}" ]]; then
  mkdir -p ${dir}
fi

# echo colors
echored="\e[31m"

# set up the colors from xrdb
BG="$bg"
FG="$fg"
BLK="$blk"
BBLK="$bblk"
RED="$red"
GRN="$grn"
YLW="$ylw"
BLU="$blu"
MAG="$mag"
CYN="$cyn"
WHT="$wht"

# gtkrc attributes; assign colors 
base_color=$WHT
nbg_color=$WHT
ntooltip_bg_color=$WHT
nselected_bg_color=$BBLK
ntext_color=$BG
nfg_color=$BG
ntooltip_fg_color=$BG
nselected_fg_color=$BG
nmenubar_bg_color=$BG
nmenubar_fg_color=$WHT
ntoolbar_bg_color=$BG
ntoolbar_fg_color=$WHT
nmenu_bg_color=$BG
nmenu_fg_color=$FG
npanel_bg_color=$BG
npanel_fg_color=$WHT
nlink_color=$BLU

# what colors are being used
palette=$(awk 'NR==2{gsub(/</," ");gsub(/>/," ");print $2}' $HOME/.Xresources | cut -d '/' -f5)

# theme directory 
themedir=$HOME/.themes

# grab currently selected theme
theme=$(cat $HOME/.gtkrc-2.0|grep "gtk-theme-name"|awk '{print}'|cut -d '=' -f2|awk '{gsub(/"/,"");print'})

# grab current theme color colors
file=$themedir/$theme/gtk-2.0/gtkrc
tmpfile=$dir/coltemp

# take colors and place into an array
for i in {1..17}
do
  gtkcol=$(cat $file|grep "_color:"|cut -d '\' -f$i|cut -d '#' -f2)
  echo $gtkcol >> $tmpfile
  arr=($(< $tmpfile))
done

# test
#echo ${arr[@]}

# action; set the new colors
sed -i "s/${arr[0]}/"$base_color"/;
        s/${arr[1]}/"$nbg_color"/;
        s/${arr[2]}/"$ntooltip_bg_color"/;
        s/${arr[3]}/"$nselected_bg_color"/;
        s/${arr[4]}/"$ntext_color"/;
        s/${arr[5]}/"$nfg_color"/;
        s/${arr[6]}/"$ntooltip_fg_color"/;
        s/${arr[7]}/"$nselected_fg_color"/;
        s/${arr[8]}/"$nmenubar_bg_color"/;
        s/${arr[9]}/"$nmenubar_fg_color"/;
        s/${arr[10]}/"$ntoolbar_bg_color"/;
        s/${arr[11]}/"$ntoolbar_fg_color"/;
        s/${arr[12]}/"$nmenu_bg_color"/;
        s/${arr[13]}/"$nmenu_fg_color"/;
        s/${arr[14]}/"$npanel_bg_color"/;
        s/${arr[15]}/"$npanel_fg_color"/;
        s/${arr[16]}/"$nlink_color'"'"/" $file

# remove temp color file
rm $tmpfile

echo ' ... gtk colors changed'
echo -e ' ... color palette used is '$echored$palette
