#!/bin/sh
## control some bar parameters in one place
## dkeg 2015

## global colors
. $HOME/bin/colr

## glyph fonts
  gly1=-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1
  gly2=-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1

  alpha2="#DC"
  alpha3="#FF"
  alpha="#FF"

## globals
  barh=28
  bary=10
  width=1366
  pbg=$alpha2$bg
  pfg=$alpha$fg
  gbg=$alpha2$ylw
  gfg=$alpha$blk

## set a base popup size  
  base=10 

## grab the font size
  size=$(xrdb -query | grep "*font"|cut -d '-' -f8)

## grab the input; get the size (thanks Wildefyr ... I think) 
  txtw -s "$base" + "$size" "$@" > /tmp/.popup

## get the final width
  barw=$(cat /tmp/.popup | awk '{for (i=1;i<=NF;++i) total += $i; print total}')

## add padding  
  bw=$((barw + 20))

## notification popups
  pop() {
    bump=$(($width - 20 - $bw)) 
    bar_x=$bump

    pop_g="${bw}x${barh}+${bar_x}+${bary}"
  }

## system status bar
  stat() {
    bar_w=900
    bump=$(($width/2 - $bar_w/2))
    bar_x=$bump

    stat_g="${bar_w}x${barh}+${bar_x}+${bary}"
  }

## and finally
  stat 
  pop 
