#! /bin/bash

## dkeg 2015
## join scrot and imgur to auto upload

## dependencies are
  # bar for popups OR use dunst and change notify accordingly
  # imgur upload script (https://code.google.com/p/imgur-cli/)
  # hit 'q' to exit the scrot preview and continue

  usage () {
    echo "usage $(basename $0) [name.png |name.jpg]"
    exit 1
  }

## globals
  scrotit='scrot -d 2'
  sendit="imgur upload $1 -t $1"
  notify="popbatt %{c}"
  success="echo Success! $1 was uploaded"

  test -n "$1" || usage

## clear the screen to look nice
  function clr() {
    echo clear
  }
  function dir() {
    pwd
  }
  function saveit() {
        echo -e "Specify a location to save or Enter to skip."
        read location
          if [ -z  $location ] ;then
            echo "saved to $(dir)"
          else
            if [ ! -d $location ]; then
              echo "$location does not exit. Bye!"
              exit 1
            else
              mv $1 $location
              $(clr) && echo ".... $1 was saved to $location"
            fi
          fi
  }
## scot it up!
    info
    $scrotit $1 & $notify ' sup' $1
    $(clr)
      echo -e "Upload to Imgur?
      a. Upload and Save
      b. Upload; don't Save
      c. Save only
      d. Delete and Quit"
    read action
      if [ $action == "a" ] ;then
          saveit $1
          cd $location
          $sendit && cd $HOME
          echo ".... $1 was uploaded."
          $(clr) && $success
          $notify "  $1 uploaded"
      elif [ $action == "b" ] ;then
          $sendit
          rm $1
          $(clr) && echo  ".... $1 was deleted."
          echo ".... $1 was uploaded."
          $(clr) && $success
          $notify "  $1 uploaded"
      elif [ $action == "c" ] ;then
          saveit $1
          $notify "  $1 was saved"
      elif [ $action == "d" ] ;then
          rm $1
          $(clr) && echo "... $1 deleted. Bye!"
          exit 0
      else
          echo "Something went wrong. Try again."
          exit 1
      fi
