#!/bin/bash

## control some bar parameters in one place
. $HOME/bin/colr

  #alpha="#A5"
  alpha="#CC"
  
  BG="$alpha$bg"
  FG="$alpha$fg"
  BLK="$alpha$blk"
  BBLK="$alpha$bblk"
  RED="$alpha$red"
  GRN="$alpha$grn"
  YLW="$alpha$ylw"
  BLU="$alpha$blu"
  MAG="$alpha$mag"
  CYN="$alpha$cyn"
  WHT="$alpha$wht"

## globals
  bar_h=28
  bar2_h=32
  bar3_h=22
  gbarbg=$YLW
  gbarfg=$BBLK
  battbbg=$RED
  battbfg=$WHT

statusbar() {
  bar_w=1100
  bar_h=$bar_h
  bar_x=140
  bar_y=4

  statusbar_g="-b -g ${bar_w}x${bar_h}+${bar_x}+${bar_y} -d -B ${bar_bg} -F ${bar_fg} -f '${font},${font2},${font3}'"
}
smallstatus() {
  bar_w=500
  bar_h=$bar2_h
  bar_x=750
  bar_y=8

  smallstatus_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
notifybar() {
  bar_w=770
  bar_h=$bar_h
  bar_x=297
  bar_y=6

  notifybar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
batbar() {
  bar_w=185
  bar_h=$bar3_h
  bar_x=1135
  bar_y=6

  batbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
musicbar() {
  bar_w=375
  bar_h=$bar2_h
  bar_x=975
  bar_y=58

  musicbar_g="-g ${bar_w}x${bar_h}+${bar_x}+${bar_y} -d -B ${bar_bg} -F ${bar_fg} -f '${font},${font2},${font3}'"
}
fullbar() {
  bar_w=866
  bar_h=$bar3_h
  bar_x=250
  bar_y=6
  
  fullbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}

chatbar() {
  bar_w=200
  bar_h=$bar3_h
  bar_x=1100
  bar_y=20

  chatbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
volbar() {
  bar_w=135
  bar_h=$bar3_h
  bar_x=1125
  bar_y=20
  
  g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
  volbar_g=$g
}
musbar() {
  bar_w=225
  bar_h=$bar3_h
  bar_x=825
  bar_y=20

  musbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}

## and finally
  statusbar
  smallstatus
  notifybar
  batbar
  musicbar
  chatbar
  volbar
  musbar
  fullbar
