#! /bin/bash

## control some bar parameters in one place

  #alpha="#A5"
  alpha="#CC"
  
  xolor(){
    echo -n "$( xrdb -query | grep "\*$1:" | grep -oE "#[a-zA-Z0-9]{6}" | cut -c 2- )";
  }

  BG="$alpha$(xolor background)"
  FG="$alpha$(xolor foreground)"
  BLK="$alpha$(xolor color0)"
  BBLK="$alpha$(xolor color8)"
  RED="$alpha$(xolor color1)"
  GRN="$alpha$(xolor color2)"
  YLW="$alpha$(xolor color3)"
  BLU="$alpha$(xolor color4)"
  MAG="$alpha$(xolor color5)"
  CYN="$alpha$(xolor color6)"
  WHT="$alpha$(xolor color7)"
  BRED="$alpha$(xolor color9)"
  BGRN="$alpha$(xolor color10)"
  BYLW="$alpha$(xolor color11)"
  BBLU="$alpha$(xolor color12)"
  BMAG="$alpha$(xolor color13)"
  BCYN="$alpha$(xolor color14)"
  BWHT="$alpha$(xolor color15)"

## grab the fonts from .Xresources
  xonts() {
    fnt=$(xrdb -query | grep font | awk '{$1="";print}'|cut -d ',' -f1)
    ico=$(xrdb -query | grep font | awk '{$1="";print}'|cut -d ',' -f2)
    fnt2=$(xrdb -query | grep font | awk '{$1="";print}'|cut -d ',' -f3)
    ico2=$(xrdb -query | grep font | awk '{$1="";print}'|cut -d ',' -f4)

    fnts=($fnt $ico $fnt2 $ico2)
}

## globals
  bar_h=28
  bar2_h=32
  bar3_h=22
  gbarbg=$YLW
  gbarfg=$BBLK
  battbbg=$RED
  battbfg=$BBLK

statusbar() {
  bar_w=1100
  bar_h=$bar_h
  bar_x=140
  bar_y=4

  statusbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
smallstatus() {
  bar_w=500
  bar_h=$bar2_h
  bar_x=750
  bar_y=8

  smallstatus_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
notifybar() {
  bar_w=770
  bar_h=$bar_h
  bar_x=297
  bar_y=6

  notifybar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
batbar() {
  bar_w=200
  bar_h=$bar2_h
  bar_x=1100
  bar_y=21

  batbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
musicbar() {
  bar_w=375
  #bar_w=$length
  bar_h=$bar2_h
  bar_x=975
  bar_y=58

  musicbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
fullbar() {
  bar_w=1266
  bar_h=$bar3_h
  bar_x=50
  bar_y=3
  
  fullbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}

chatbar() {
  bar_w=200
  bar_h=$bar3_h
  bar_x=1100
  bar_y=20

  chatbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
volbar() {
  bar_w=135
  bar_h=$bar3_h
  bar_x=1125
  bar_y=20

  volbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}
musbar() {
  bar_w=275
  bar_h=$bar3_h
  bar_x=825
  bar_y=20

  musbar_g="${bar_w}x${bar_h}+${bar_x}+${bar_y}"
}

## and finally
  statusbar
  smallstatus
  notifybar
  batbar
  musicbar
  chatbar
  volbar
  musbar
  fullbar
  xonts
