#!/bin/bash
# dkeg 2015
# inspiration from z3bra
# give me battery notifications 
# sourced from battbar 

. $HOME/bin/barconf

duration=6

# colors and fonts
# sourced from barconf

# put it together 
baropt='-g '${batbar_g}' -d -F '${battbfg}' -B '${battbbg}' -f '${fnts[0]},${fnts[1]}''

# create it 
(echo " $@"; sleep ${duration}) | bar ${baropt}
