#!/bin/bash
# dkeg 2015
# inspiration from z3bra
# notification used with irssi and weechat
# source from notify.pl and notify.rb
# both altered to use this over notify-send 

. $HOME/bin/barconf

duration=6

# colors and fonts
# source from barconf

# put it together 
baropt='-b -g '${chatbar_g}' -d -F '${gbarfg}' -B '${gbarbg}' -f '${fnts[0]},${fnts[1]}''

# create it
(echo " $@"; sleep ${duration}) | bar ${baropt}
