#!/bin/bash
# dkeg 2015
# inspiration from z3bra
# cmus actions notification
# play,pause,next,previous

. $HOME/bin/barconf

duration=3

# colors
bar_bg=$YLW
bar_fg=$BBLK

# font
font=${fnts[0]}
font2=${fnts[1]}
font3=${fnts[3]} 

# put it together
baropt='-b -g '${musbar_g}' -d -F '${bar_fg}' -B '${bar_bg}' -f '${font},${font2},${font3}''

# Create it 
(echo "$@ "; sleep ${duration}) | bar ${baropt} 
