#!/bin/bash
# dkeg 2015
# inspiration from z3bra
# cmus actions notification
# play,pause,next,previous

. $HOME/bin/barconf

duration=3

# colors and fonts
# sourced from barconf

# put it together
baropt='-b -g '${musbar_g}' -d -F '${gbarfg}' -B '${gbarbg}' -f '${fnts[0]},${fnts[1]}''

# Create it 
(echo "$@ "; sleep ${duration}) | bar ${baropt} 
