#!/bin/bash
# dkeg 2015
# inspiration from z3bra
# song notifications with cmus
# sourced from cmus_notifiy.py
# altered to use this over notify-send

. $HOME/bin/barconf

duration=3

# colors and fonts
# sourced from  barconf

# put it together 
baropt='-g '${fullbar_g}' -d -F '${gbarfg}' -B '${gbarbg}' -f '${fnts[0]}''

# create it
(echo " $@"; sleep ${duration}) | bar ${baropt}
