#!/bin/bash
# dkeg 2015
# inspiration from z3bra
# song notifications with cmus
# sourced from cmus_notifiy.py
# altered to use this over notify-send

. $HOME/bin/barconf

duration=2

# colors
bar_bg=$YLW
bar_fg=$BBLK

# font
font=${fnts[0]}
font2=${fnts[2]}
ico=${fnts[1]}
ico2=${fnts[3]}

# put it together 
baropt='-g '${fullbar_g}' -d -F '${bar_fg}' -B '${bar_bg}' -f '${font},${font2},${ico},${ico2}''

# create it
(echo " $@"; sleep ${duration}) | bar ${baropt}
