#!/bin/bash
# dkeg 2015
# inspiration from z3bra
# notification of volume events 
# sourced from .xbindkeysrc and volume

. $HOME/bin/barconf

duration=3

# colors and fonts
# source from barconf

# put it together
baropt='-b -g '${volbar_g}' -d -F '${gbarfg}' -B '${gbarbg}' -f '${fnts[0]},${fnts[1]}''

# create it 
(echo "$@ "; sleep ${duration}) | bar ${baropt} 
